### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Jonny2579** [Gamebunn/Cream64_PC#1]
I got this message while compiling the game.

> You should specify a coefficient codebook with the [-c] option
make: *** [Makefile:1504: build/us_pc/sound/samples/streamed_audio_main/bbh_hangcastle1_0.aifc] Error 1

I was able to successfully compile the sm64ex repo, so I'm unsure if it is due to user error or something breaking. I've attached a screenshot of the last output and and a .txt of my output. I'm new to compiling programs like this so forgive me if I made rookie mistakes. 
![mintty 2023-03-21_02-19-27](https://user-images.githubusercontent.com/128454745/226531613-0e009db1-0676-4d69-95a7-a6f12b91a7f1.png)
[output.txt](https://github.com/Gamebunn/Cream64_PC/files/11025423/output.txt)

**Comment by Gamebunn** [comment]
The last time I've ran into this issue compiling right after did just make it work so I have no idea what suddenly causes it to act up. If you wanna try, I've added a new zip folder that has the sounds compiled so that might bypass the need to compile those new sounds. Check out the readme's FAQ.

**Comment by Jonny2579** [comment]
That did the trick, thank you
