### ISSUE TITLE
Frequent Crashes

### ISSUE THREAD

**Issue by KamyKam7** [Gamebunn/Cream64_PC#2]
I'm not sure how to really describe this, but I have ran into frequent crashes for some odd reason. I have no idea what's causing this at all and I hope I can somehow submit a log file of some sort but I have no idea how. 

The one thing I can say is that I consistently crash if I run into the fire on Bowsers first level for some reason. 

Edit: I think it might be an input issue, because after trying to see if there was something wrong with my controller, I found out I have the unique ability to crash the game at will by pressing left shift. 

Edit 2:Yeah i definitely think its a input issue. I used a controller and for some reason, R2, L1, and R1 crash the game 
I'm using DS4Windows btw to control the game, not sure how relevant it is. 

I still think it might be something wrong with the game itself too since running into the fire on Bowser's first level still crashes the game.

**Comment by AloXado320** [comment]
If you delete `sm64config.txt` does input still crash?

If you are on Windows, you can send an screenshot of the crash screen.

**Comment by KamyKam7** [comment]
I'll have to try that, deleting that config file might work.

Btw I "kinda" fixed it.

See I originally compiled the game on my normal C drive where I run windows. I usually play my games on my second ssd so I copied it over there on my D drive and kept the original game on my C drive. 

I don't know why but I tried to play it on the C drive again and it worked a hell of a lot better. No input crashing from pressing certain buttons, no fire burning me crashing at the start of Bowser's first fortress. 

I WILL say that I still had a few random crashes from out of nowhere still. I could still play the game for a long enough amount of time (I think the longest was about an hour (ps. Im kinda addicted to this mod)), but I still had some crashes. Some as early as 5 minutes into the game. 

Maybe its the way I compiled it. The guide said to build the game with msys2, and for some reason it wasn't working. It kept saying it was a bad rom, even though I literally compiled and built a perfectly working normal version of sm64 to test it out. 

So what I did, for some reason was build the game using mingw64. I did it because thats the way I built the normal version of sm64. The Mod tells me to build it using msys2. So I just did it with the former and it worked. 

Sooo maybe that's why it doesn't work? I'm not sure I don't really know too much about this stuff. 

Also I did a 30 star run of this game and I got this error screen as well.
![Screenshot (1594)](https://github.com/Gamebunn/Cream64_PC/assets/141538716/19b4e166-394a-46f6-893e-cb4b0b76d0ca)

**Comment by AloXado320** [comment]
What was the last action you did before the crash?

**Comment by KamyKam7** [comment]
I got 31 red rings and I did the BLJ glitch to get to Eggman early. I beat the game and then after the credits it crashed.

**Comment by AloXado320** [comment]
Me and Gamebunn couldn't get any crashes.

You said that you had to install/compile the repo using different steps, i use mingw64 and it works fine there.

Worst case scenario maybe your msys installation is either outdated or somehow corrupted so you better off reinstalling it.

**Comment by KamyKam7** [comment]
These are the versions of the installations that I have, according to the details. 

![image](https://github.com/Gamebunn/Cream64_PC/assets/141538716/4ef35d55-5629-43eb-ad7b-10b479ae803c)
![image](https://github.com/Gamebunn/Cream64_PC/assets/141538716/f0f2df23-8e87-4369-8988-82cba7bf6ad4)

**Comment by AloXado320** [comment]
So those are latest versions i see.

Have you tried to do `make clean`? I want to make sure it only happened during a clean build.

If you can, you can send a video before the crash.

**Comment by KamyKam7** [comment]
Here is my video I made that contains multiple crashes, and the crash I was talking about that I get when I beat the game with the BLJ glitch. I did a COMPLETE reinstall before I did this. I reinstalled Msys2, compiled another version of sm64, and also compiled this with the high fps patch and the no draw distance.  And just like before, when I built the game I built it with MINGW64 instead of MSYS2. MSYS2 still said it was a bad rom so thats why I went with MINGW64 again, but I think according to you guys, thats not a problem. 

I also wanna add that the game does not like OBS. Or at least when it crashes, since the recording froze after crashing outside Peach's Castle, but the audio was still there. Which is the reason why I just recorded my entire screen afterwards. 

https://www.youtube.com/watch?v=SJVM2gwUFxc

**Comment by Gamebunn** [comment]
That's still a strange thing to happen (especially those random crashes in the video) but I wanna try one more thing before I go with this last option. Can you post the error that you get in MSYS2? Curious if there's anything else to the bad rom error that can help us.

**Comment by KamyKam7** [comment]
When I try to make it in MSYS2, I usually get this error message. 

![Screenshot (1602)](https://github.com/Gamebunn/Cream64_PC/assets/141538716/9efd8e0b-f1e5-44bc-b842-4f3419a1abe4)

**Comment by Gamebunn** [comment]
So I'm just realizing you have been using the right compiler (I keep forgetting the blue one is MinGW which is the right one). I did more playtesting around the areas you showed off and still no real idea as to why you're getting these crashes specifically.

**Comment by AloXado320** [comment]
So the issue has been confirmed to happen on specific parts of TTC (particularly red coins and blue coins part).

I'm testing fixes for those crashes.

**Comment by AloXado320** [comment]
Fixed on ee1dd3a

@Gamebunn and I confirm there are no crashes so far, confirm @KamyKam7 so we can close this issue.

**Comment by KamyKam7** [comment]
I believe the issue is fixed now. Time to finally put a close on this page of the book.

**Comment by KamyKam7** [comment]
I believe the issue is fixed now. Time to finally put a close on this page of the book.
