### ISSUE TITLE
Unable to remap controls whatsoever!

### ISSUE THREAD

**Issue by Adaman120** [Gamebunn/Cream64_PC#3]
Hello,

I recently compiled Super Cream 64 on Windows 10. While attempting to rebind the controls to my liking, I accidentally messed up by binding multiple functions to the same button(s). I tried to unbind everything in an attempt to "start over" and rebind my buttons correctly. (Strangely, the right trigger on my Xbox One controller deleted existing binds, so I just used that until everything was set to NONE.)

Now I'm completely locked out of interacting with the game. Nothing on my keyboard works, and nothing on my controller works. I can boot up the game just fine, but cannot proceed past the "Press Start" screen. I've tried uninstalling / reinstalling SC64, SM64EX, MYSYS2, everything. Nothing works, which leads me to believe the config file for SC64 is stored somewhere outside of the aforementioned filepaths. Any help would be greatly appreciated.

1) Open SC64
2) Once in-game, open the pause menu, and hit R to open the options menu
3) Select Buttons
4) Unbind all buttons from each column and row
5) Suffering

If you need any additional information, feel free to ask. I'm inexperienced, but I'll provide as much detail as I can.

**Comment by Adaman120** [comment]
After doing some digging, I found the solution to the problem.

I navigated to my Appdata / Roaming / sm64ex folder. Inside it is cream64.bin and sm64config.txt

Deleting both of them will revert the game to it's default configuration settings. Hope this helps!

**Comment by Gamebunn** [comment]
Yeah, figuring out how to unbind is something I'm not even sure either so if it ever got to that point, I just delete sm64config.txt. You don't have to delete cream64.bin since it's just the save data for the stars and not any of the configs but to each their own. Since the problem has been solved, I'll go ahead and close this.
